print("Syed Ahsan Hussain")
print("Syed Iqtedar Hussain")
print("Nationality: Pakistani")
print("NIC # 42501-6175618-3")
print("Zubair Azeeme")
print("Sir Qasim Ali")
print("I have Laptop Dell Latitude E6410")
print("Saylani Welfare Trust")
print("PIAIC")
print("A.I")
